#! /usr/env bash

# versions
ROS_DISTRO="foxy"

# paths
LOGS_PATH="logs"

# git 
DOCKER_URL="https://github.com/Federico-Ciuffardi/docker-cocosim"
DOCKER_BRANCH="master"

EXAMPLES_URL="git@gitlab.fing.edu.uy:cocosim/code/ejemplos"
EXAMPLES_BRANCH="master"

LAUNCH_URL="https://github.com/ros2/launch.git"
LAUNCH_BRANCH="$ROS_DISTRO"

MODIFIED_LAUNCH_ROS_URL="https://github.com/Federico-Ciuffardi/launch_ros.git"
MODIFIED_LAUNCH_ROS_BRANCH="cocosim-$ROS_DISTRO"

RWM_URL="https://github.com/ros2/rmw.git"
RWM_BRANCH="$ROS_DISTRO"

RWM_DDS_COMMON_URL="https://github.com/ros2/rmw_dds_common.git"
RWM_DDS_COMMON_BRANCH="$ROS_DISTRO"

MODIFIED_RMW_CYCLONEDDS_URL="https://github.com/Federico-Ciuffardi/rmw_cyclonedds.git"
MODIFIED_RMW_CYCLONEDDS_BRANCH="cocosim-$ROS_DISTRO"

MODIFIED_CYCLONEDDS_URL="https://github.com/Federico-Ciuffardi/cyclonedds.git"
MODIFIED_CYCLONEDDS_BRANCH="cocosim-0.7.0"

COCOSIM_CYCLONEDDS_URL="git@gitlab.fing.edu.uy:cocosim/code/cocosim-cyclonedds"
COCOSIM_CYCLONEDDS_BRANCH="master"

COCOSIM_GAZEBO_PLUGIN_URL="git@gitlab.fing.edu.uy:cocosim/code/cocosim-gazebo-plugin"
COCOSIM_GAZEBO_PLUGIN_BRANCH="master"

COCOSIM_GAZEBO_PLUGIN_URL="git@gitlab.fing.edu.uy:cocosim/code/cocosim-gazebo-plugin"
COCOSIM_GAZEBO_PLUGIN_BRANCH="master"

NS3_SERVICE_URL="https://gitlab.fing.edu.uy/fvelazquez/proto-ns3-service"
NS3_SERVICE_BRANCH="main"

# misc
DOCKER="true" 
AUR_HELPER="yay"
# DEBUG="logs" # [logs, gdb, valgind]
